"""add protected flag to services and tire offer declined to bookings

Revision ID: 151f2fa88e1c
Revises: 9618c1251981
Create Date: 2026-09-16 15:17:01.514373

"""
from alembic import op
import sqlalchemy as sa


revision = '151f2fa88e1c'
down_revision = '9618c1251981'
branch_labels = None
depends_on = None


SEASONAL_TIRE_SWAP_SERVICE_NAME = "Сезонная замена шин"
TIRE_VISIT_SERVICE_NAME = "Получить/сдать шины"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('tire_offer_declined', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('services', sa.Column('protected', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # UI_description.md п.47 (2026-09-16): хранение шин теперь возможно
    # только как часть настоящего визита на одну из этих двух услуг — не
    # просто кликом в кабинете (см. app/api/tire_sets.py). Тот же приём, что
    # и посты (dfe1c685b738) — фиксированные строки, не через обычный CRUD.
    services = sa.table(
        "services",
        sa.column("name", sa.String),
        sa.column("duration_minutes", sa.Integer),
        sa.column("price", sa.Numeric),
        sa.column("protected", sa.Boolean),
    )
    op.bulk_insert(
        services,
        [
            {
                "name": SEASONAL_TIRE_SWAP_SERVICE_NAME,
                "duration_minutes": 40,
                "price": 1200.00,
                "protected": True,
            },
            {
                "name": TIRE_VISIT_SERVICE_NAME,
                "duration_minutes": 10,
                "price": 100.00,
                "protected": True,
            },
        ],
    )


def downgrade() -> None:
    services = sa.table("services", sa.column("name", sa.String))
    op.execute(
        services.delete().where(
            services.c.name.in_([SEASONAL_TIRE_SWAP_SERVICE_NAME, TIRE_VISIT_SERVICE_NAME])
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'protected')
    op.drop_column('bookings', 'tire_offer_declined')
    # ### end Alembic commands ###
