"""add service_ends_at to bookings

Revision ID: 2d4b41723199
Revises: 635da70bf62c
Create Date: 2026-09-13 18:24:37.193684

"""
from alembic import op
import sqlalchemy as sa


revision = '2d4b41723199'
down_revision = '635da70bf62c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('service_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'service_ends_at')
    # ### end Alembic commands ###
