"""add outbox email stub table

Revision ID: 3253e3309772
Revises: a36ec12a35ca
Create Date: 2026-09-13 17:20:52.673000

"""
from alembic import op
import sqlalchemy as sa


revision = '3253e3309772'
down_revision = 'a36ec12a35ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_emails_to'), 'outbox_emails', ['to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_emails_to'), table_name='outbox_emails')
    op.drop_table('outbox_emails')
    # ### end Alembic commands ###
