"""add reminder_sent to bookings

Revision ID: 3b23bb98fef6
Revises: 2d4b41723199
Create Date: 2026-09-13 19:01:24.461687

"""
from alembic import op
import sqlalchemy as sa


revision = '3b23bb98fef6'
down_revision = '2d4b41723199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_sent')
    # ### end Alembic commands ###
