"""add parking spots, station settings, and parking fields to bookings

Revision ID: 41f8d31fc7be
Revises: 151f2fa88e1c
Create Date: 2026-09-17 15:51:19.365974

"""
from alembic import op
import sqlalchemy as sa


revision = '41f8d31fc7be'
down_revision = '151f2fa88e1c'
branch_labels = None
depends_on = None


# C7 (buisness.md, "Smart Parking Management", 2026-09-17): 6 фиксированных
# мест ожидания — тот же приём, что и посты (dfe1c685b738_seed_default_
# posts.py) и защищённые услуги хранения шин (151f2fa88e1c) — заведены
# прямо в миграции, не через обычный CRUD, потому что это фиксированная
# физическая конфигурация станции, а не пользовательские данные.
PARKING_SPOT_NAMES = [f"Место {i}" for i in range(1, 7)]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('station_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_overdue_rate_per_minute', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('parking_spot_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('parked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('parking_wait_before_minutes', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_bookings_parking_spot_id'), 'bookings', ['parking_spot_id'], unique=False)
    # Явное имя ограничения (не None) — иначе downgrade() не может надёжно
    # его найти для drop_constraint (тот же урок, что и в остальных
    # миграциях этого проекта с FK, добавленными после create_table).
    op.create_foreign_key(
        'fk_bookings_parking_spot_id', 'bookings', 'parking_spots', ['parking_spot_id'], ['id']
    )
    # ### end Alembic commands ###

    parking_spots = sa.table("parking_spots", sa.column("name", sa.String))
    op.bulk_insert(parking_spots, [{"name": name} for name in PARKING_SPOT_NAMES])

    station_settings = sa.table(
        "station_settings", sa.column("id", sa.Integer), sa.column("parking_overdue_rate_per_minute", sa.Numeric)
    )
    op.bulk_insert(station_settings, [{"id": 1, "parking_overdue_rate_per_minute": 5.00}])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_parking_spot_id', 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_parking_spot_id'), table_name='bookings')
    op.drop_column('bookings', 'parking_wait_before_minutes')
    op.drop_column('bookings', 'parked_at')
    op.drop_column('bookings', 'parking_spot_id')
    op.drop_table('station_settings')
    op.drop_table('parking_spots')
    # ### end Alembic commands ###
