"""add duration and execution tracking to additional works

Revision ID: 520e13e2663b
Revises: 3b23bb98fef6
Create Date: 2026-09-13 19:06:29.248223

"""
from alembic import op
import sqlalchemy as sa


revision = '520e13e2663b'
down_revision = '3b23bb98fef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_works', sa.Column('duration_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('additional_works', sa.Column('execution_started', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additional_works', 'execution_started')
    op.drop_column('additional_works', 'duration_minutes')
    # ### end Alembic commands ###
