"""add additional works snapshot to booking archive

Revision ID: 635da70bf62c
Revises: 3253e3309772
Create Date: 2026-09-13 17:26:06.778928

"""
from alembic import op
import sqlalchemy as sa


revision = '635da70bf62c'
down_revision = '3253e3309772'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен, т.к. в таблице уже есть реальные записи (журнал
    # заявок пользователя) — NOT NULL без дефолта уронил бы миграцию на
    # существующих строках.
    op.add_column(
        'booking_archive',
        sa.Column(
            'additional_works_snapshot',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_archive', 'additional_works_snapshot')
    # ### end Alembic commands ###
