"""add mileage_at_last_service to cars

Revision ID: 707ca94922e7
Revises: e81b2bb43baf
Create Date: 2026-09-14 18:24:49.995372

"""
from alembic import op
import sqlalchemy as sa


revision = '707ca94922e7'
down_revision = 'e81b2bb43baf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mileage_at_last_service', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'mileage_at_last_service')
    # ### end Alembic commands ###
