"""add on_post_started_at to bookings

Revision ID: 85e4d5a94767
Revises: ae80688705b5
Create Date: 2026-09-15 21:14:03.531491

"""
from alembic import op
import sqlalchemy as sa


revision = '85e4d5a94767'
down_revision = 'ae80688705b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('on_post_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'on_post_started_at')
    # ### end Alembic commands ###
