"""add ai confidence and reason to additional works

Revision ID: 9618c1251981
Revises: 85e4d5a94767
Create Date: 2026-09-16 15:06:31.929649

"""
from alembic import op
import sqlalchemy as sa


revision = '9618c1251981'
down_revision = '85e4d5a94767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_works', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('additional_works', sa.Column('ai_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additional_works', 'ai_reason')
    op.drop_column('additional_works', 'ai_confidence')
    # ### end Alembic commands ###
