"""add booking archive journal

Revision ID: a3236cb2b460
Revises: f78e99dcbbed
Create Date: 2026-09-12 22:55:46.586363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'a3236cb2b460'
down_revision = 'f78e99dcbbed'
branch_labels = None
depends_on = None

# Переиспользуем уже существующий тип booking_status (создан в
# 909e4725fc6d) — create_type=False, иначе CREATE TYPE упадёт с
# DuplicateObjectError, т.к. тип уже есть в БД (тот же класс проблемы, что
# уже чинили для downgrade() в более ранних миграциях).
booking_status_enum = postgresql.ENUM(
    'ACCEPTED', 'ON_POST', 'AWAITING_APPROVAL', 'READY', 'ISSUED', 'CANCELLED',
    name='booking_status',
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_booking_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_make', sa.String(), nullable=False),
    sa.Column('car_model', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', booking_status_enum, nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('services_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_archive_client_id'), 'booking_archive', ['client_id'], unique=False)
    op.create_index(op.f('ix_booking_archive_original_booking_id'), 'booking_archive', ['original_booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_archive_original_booking_id'), table_name='booking_archive')
    op.drop_index(op.f('ix_booking_archive_client_id'), table_name='booking_archive')
    op.drop_table('booking_archive')
    # ### end Alembic commands ###
