"""one active tire set per car

Revision ID: a36ec12a35ca
Revises: a3236cb2b460
Create Date: 2026-09-13 16:49:02.628078

"""
from alembic import op
import sqlalchemy as sa


revision = 'a36ec12a35ca'
down_revision = 'a3236cb2b460'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tire_sets_one_active_per_car', 'tire_sets', ['car_id'], unique=True, postgresql_where=sa.text('issued_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tire_sets_one_active_per_car', table_name='tire_sets', postgresql_where=sa.text('issued_at IS NULL'))
    # ### end Alembic commands ###
