"""add tire season reminder dismissed season to clients

Revision ID: ae80688705b5
Revises: b0dec29c14ba
Create Date: 2026-09-15 18:56:09.074864

"""
from alembic import op
import sqlalchemy as sa


revision = 'ae80688705b5'
down_revision = 'b0dec29c14ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tire_season_reminder_dismissed_season', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'tire_season_reminder_dismissed_season')
    # ### end Alembic commands ###
