"""tire sets and additional works

Revision ID: c1528f5a8b01
Revises: 909e4725fc6d
Create Date: 2026-09-11 14:28:32.596204

"""
from alembic import op
import sqlalchemy as sa


revision = 'c1528f5a8b01'
down_revision = '909e4725fc6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tire_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tire_sets_car_id'), 'tire_sets', ['car_id'], unique=False)
    op.create_index(op.f('ix_tire_sets_client_id'), 'tire_sets', ['client_id'], unique=False)
    op.create_table('additional_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proposed_by', sa.Enum('MECHANIC', 'AI', name='proposed_by'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='additional_work_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_works_booking_id'), 'additional_works', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_additional_works_booking_id'), table_name='additional_works')
    op.drop_table('additional_works')
    op.drop_index(op.f('ix_tire_sets_client_id'), table_name='tire_sets')
    op.drop_index(op.f('ix_tire_sets_car_id'), table_name='tire_sets')
    op.drop_table('tire_sets')
    # ### end Alembic commands ###
    # Autogenerate не эмитит drop для Postgres ENUM-типов — без этих строк
    # downgrade+upgrade падает на "type ... already exists" (см. аналогичный
    # фикс в 909e4725fc6d_initial_schema.py).
    sa.Enum(name='additional_work_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='proposed_by').drop(op.get_bind(), checkfirst=True)
