"""add tire_set_archive table

Revision ID: e81b2bb43baf
Revises: 520e13e2663b
Create Date: 2026-09-14 16:34:15.610001

"""
from alembic import op
import sqlalchemy as sa


revision = 'e81b2bb43baf'
down_revision = '520e13e2663b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tire_set_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_tire_set_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_make', sa.String(), nullable=False),
    sa.Column('car_model', sa.String(), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tire_set_archive_client_id'), 'tire_set_archive', ['client_id'], unique=False)
    op.create_index(op.f('ix_tire_set_archive_original_tire_set_id'), 'tire_set_archive', ['original_tire_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tire_set_archive_original_tire_set_id'), table_name='tire_set_archive')
    op.drop_index(op.f('ix_tire_set_archive_client_id'), table_name='tire_set_archive')
    op.drop_table('tire_set_archive')
    # ### end Alembic commands ###
