"""add station stats revenue counter

Revision ID: f78e99dcbbed
Revises: c081a0d950c1
Create Date: 2026-09-12 22:42:08.293178

"""
from alembic import op
import sqlalchemy as sa


revision = 'f78e99dcbbed'
down_revision = 'c081a0d950c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Единственная строка-счётчик (id=1) — заведена заранее, чтобы
    # UPDATE ... WHERE id=1 в коде приложения всегда находил её.
    station_stats = sa.table(
        "station_stats", sa.column("id", sa.Integer), sa.column("total_revenue", sa.Numeric)
    )
    op.bulk_insert(station_stats, [{"id": 1, "total_revenue": 0}])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_stats')
    # ### end Alembic commands ###
